name: Deploy CloudBotIRC to Bots EC2 Instance.

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenSSH and rsync
        run: |
          sudo apt-get install -y openssh-client rsync

      - name: Start SSH Agent and Add Key
        run: |
          mkdir -p $HOME/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_ed25519_${{ secrets.SSH_USER }}
          chmod 600 $HOME/.ssh/id_ed25519_${{ secrets.SSH_USER }}

      - name: Add EC2 instance to known hosts
        run: |
          ssh-keyscan -t ed25519 ${{ secrets.SSH_HOST }} >> $HOME/.ssh/known_hosts

      - name: Sync files to EC2 using rsync
        run: |
          rsync -avz --delete --exclude='.git' $HOME/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}
